name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Profile README with commits
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
          COMMIT_MSG: "⚡ Update README with recent commits"
          FILTER_EVENTS: "PushEvent"
          COMMIT_NAME: "santiagoencodigo"
          COMMIT_EMAIL: "159667940+santiagoencodigo@users.noreply.github.com"