name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Profile README with commits
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: santiagoencodigo
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          MAX_LINES: 5
          EVENT_TYPE: "commit"
          COMMIT_MSG: "⚡ Update README with recent commits"
          COMMIT_NAME: "santiagoencodigo"
          COMMIT_EMAIL: "159667940+santiagoencodigo@users.noreply.github.com"