name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: "santiagoencodigo"
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          EVENT_LIMIT: 5
          COMMIT_MESSAGE: "⚡ Update README with recent commits"
          IGNORE_EVENTS: '["CreateEvent", "IssuesEvent", "PullRequestEvent", "ReleaseEvent", "ForkEvent", "CommitCommentEvent", "IssueCommentEvent", "PullRequestReviewEvent", "PullRequestReviewCommentEvent", "RepositoryEvent", "WatchEvent", "StarEvent", "PublicEvent", "GollumEvent", "SponsorshipEvent"]'